/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "database.h"

SWIGINTERN int MyDatabase_callFPtr(struct MyDatabase *self,char const *name){
    return (*(self->fPtr))(self, name);
  }

static struct MyDatabase *new_MyDatabaseHandle() { 
  return (struct MyDatabase *) calloc(1,sizeof(struct MyDatabase)); 
}

static struct MyDatabase *copy_MyDatabaseHandle(struct MyDatabase value) { 
  struct MyDatabase *obj = (struct MyDatabase *) calloc(1,sizeof(struct MyDatabase));
  *obj = value;
  return obj; 
}

static void delete_MyDatabaseHandle(struct MyDatabase *obj) { 
  if (obj) free(obj); 
}

static void MyDatabaseHandle_assign(struct MyDatabase *obj, struct MyDatabase value) {
  *obj = value;
}

static struct MyDatabase MyDatabaseHandle_value(struct MyDatabase *obj) {
  return *obj;
}


static struct MyCollection * *new_MyCollectionHandle() { 
  return (struct MyCollection * *) calloc(1,sizeof(struct MyCollection *)); 
}

static struct MyCollection * *copy_MyCollectionHandle(struct MyCollection * value) { 
  struct MyCollection * *obj = (struct MyCollection * *) calloc(1,sizeof(struct MyCollection *));
  *obj = value;
  return obj; 
}

static void delete_MyCollectionHandle(struct MyCollection * *obj) { 
  if (obj) free(obj); 
}

static void MyCollectionHandle_assign(struct MyCollection * *obj, struct MyCollection * value) {
  *obj = value;
}

static struct MyCollection * MyCollectionHandle_value(struct MyCollection * *obj) {
  return *obj;
}


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_gg_hc_mydatabase_databaseJNI_MyCollection_1name_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct MyCollection *arg1 = (struct MyCollection *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct MyCollection **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->name);
    if (arg2) {
      arg1->name = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->name, (const char *)arg2);
    } else {
      arg1->name = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_gg_hc_mydatabase_databaseJNI_MyCollection_1name_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  struct MyCollection *arg1 = (struct MyCollection *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct MyCollection **)&jarg1; 
  result = (char *) ((arg1)->name);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_gg_hc_mydatabase_databaseJNI_new_1MyCollection(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct MyCollection *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct MyCollection *)calloc(1, sizeof(struct MyCollection));
  *(struct MyCollection **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_gg_hc_mydatabase_databaseJNI_delete_1MyCollection(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct MyCollection *arg1 = (struct MyCollection *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct MyCollection **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_gg_hc_mydatabase_databaseJNI_MyDatabase_1name_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  struct MyDatabase *arg1 = (struct MyDatabase *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct MyDatabase **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    free(arg1->name);
    if (arg2) {
      arg1->name = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->name, (const char *)arg2);
    } else {
      arg1->name = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_gg_hc_mydatabase_databaseJNI_MyDatabase_1name_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  struct MyDatabase *arg1 = (struct MyDatabase *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct MyDatabase **)&jarg1; 
  result = (char *) ((arg1)->name);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_gg_hc_mydatabase_databaseJNI_MyDatabase_1fPtr(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg3) {
  jint jresult = 0 ;
  struct MyDatabase *arg1 = (struct MyDatabase *) 0 ;
  struct MyDatabase *arg2 = (struct MyDatabase *) 0 ;
  char *arg3 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg2=NULL;
  arg1 = *(struct MyDatabase **)&jarg1; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  {
    arg2 = arg1;
  }
  result = (int)(arg1)->fPtr((struct MyDatabase const *)arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_gg_hc_mydatabase_databaseJNI_MyDatabase_1collectionFPtr(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg3, jlong jarg4) {
  jint jresult = 0 ;
  struct MyDatabase *arg1 = (struct MyDatabase *) 0 ;
  struct MyDatabase *arg2 = (struct MyDatabase *) 0 ;
  char *arg3 = (char *) 0 ;
  struct MyCollection **arg4 = (struct MyCollection **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg2=NULL;
  arg1 = *(struct MyDatabase **)&jarg1; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = *(struct MyCollection ***)&jarg4; 
  {
    arg2 = arg1;
  }
  result = (int)(arg1)->collectionFPtr((struct MyDatabase const *)arg2,(char const *)arg3,(struct MyCollection const **)arg4);
  jresult = (jint)result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_gg_hc_mydatabase_databaseJNI_MyDatabase_1callFPtr(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jint jresult = 0 ;
  struct MyDatabase *arg1 = (struct MyDatabase *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct MyDatabase **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)MyDatabase_callFPtr(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_gg_hc_mydatabase_databaseJNI_new_1database(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  struct MyDatabase *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (struct MyDatabase *)new_database(arg1);
  *(struct MyDatabase **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_gg_hc_mydatabase_databaseJNI_call_1database_1fPtr(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jint jresult = 0 ;
  struct MyDatabase *arg1 = (struct MyDatabase *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct MyDatabase **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)call_database_fPtr(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_gg_hc_mydatabase_databaseJNI_new_1MyDatabaseHandle(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct MyDatabase *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct MyDatabase *)new_MyDatabaseHandle();
  *(struct MyDatabase **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_gg_hc_mydatabase_databaseJNI_copy_1MyDatabaseHandle(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct MyDatabase arg1 ;
  struct MyDatabase *argp1 ;
  struct MyDatabase *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(struct MyDatabase **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null struct MyDatabase");
    return 0;
  }
  arg1 = *argp1; 
  result = (struct MyDatabase *)copy_MyDatabaseHandle(arg1);
  *(struct MyDatabase **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_gg_hc_mydatabase_databaseJNI_delete_1MyDatabaseHandle(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct MyDatabase *arg1 = (struct MyDatabase *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct MyDatabase **)&jarg1; 
  delete_MyDatabaseHandle(arg1);
}


SWIGEXPORT void JNICALL Java_gg_hc_mydatabase_databaseJNI_MyDatabaseHandle_1assign(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  struct MyDatabase *arg1 = (struct MyDatabase *) 0 ;
  struct MyDatabase arg2 ;
  struct MyDatabase *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct MyDatabase **)&jarg1; 
  argp2 = *(struct MyDatabase **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null struct MyDatabase");
    return ;
  }
  arg2 = *argp2; 
  MyDatabaseHandle_assign(arg1,arg2);
}


SWIGEXPORT jlong JNICALL Java_gg_hc_mydatabase_databaseJNI_MyDatabaseHandle_1value(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct MyDatabase *arg1 = (struct MyDatabase *) 0 ;
  struct MyDatabase result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct MyDatabase **)&jarg1; 
  result = MyDatabaseHandle_value(arg1);
  {
    struct MyDatabase * resultptr = (struct MyDatabase *) malloc(sizeof(struct MyDatabase));
    memmove(resultptr, &result, sizeof(struct MyDatabase));
    *(struct MyDatabase **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_gg_hc_mydatabase_databaseJNI_new_1MyCollectionHandle(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct MyCollection **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct MyCollection **)new_MyCollectionHandle();
  *(struct MyCollection ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_gg_hc_mydatabase_databaseJNI_copy_1MyCollectionHandle(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct MyCollection *arg1 = (struct MyCollection *) 0 ;
  struct MyCollection **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct MyCollection **)&jarg1; 
  result = (struct MyCollection **)copy_MyCollectionHandle(arg1);
  *(struct MyCollection ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_gg_hc_mydatabase_databaseJNI_delete_1MyCollectionHandle(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct MyCollection **arg1 = (struct MyCollection **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct MyCollection ***)&jarg1; 
  delete_MyCollectionHandle(arg1);
}


SWIGEXPORT void JNICALL Java_gg_hc_mydatabase_databaseJNI_MyCollectionHandle_1assign(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  struct MyCollection **arg1 = (struct MyCollection **) 0 ;
  struct MyCollection *arg2 = (struct MyCollection *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(struct MyCollection ***)&jarg1; 
  arg2 = *(struct MyCollection **)&jarg2; 
  MyCollectionHandle_assign(arg1,arg2);
}


SWIGEXPORT jlong JNICALL Java_gg_hc_mydatabase_databaseJNI_MyCollectionHandle_1value(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct MyCollection **arg1 = (struct MyCollection **) 0 ;
  struct MyCollection *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct MyCollection ***)&jarg1; 
  result = (struct MyCollection *)MyCollectionHandle_value(arg1);
  *(struct MyCollection **)&jresult = result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

