/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gg.hc.mydatabase;

public class database {
  public static SWIGTYPE_p_MyDatabase new_database(String name) {
    long cPtr = databaseJNI.new_database(name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_MyDatabase(cPtr, false);
  }

  public static int call_database_fPtr(SWIGTYPE_p_MyDatabase db, String name) {
    return databaseJNI.call_database_fPtr(SWIGTYPE_p_MyDatabase.getCPtr(db), name);
  }

  public static SWIGTYPE_p_MyDatabase new_MyDatabaseHandle() {
    long cPtr = databaseJNI.new_MyDatabaseHandle();
    return (cPtr == 0) ? null : new SWIGTYPE_p_MyDatabase(cPtr, false);
  }

  public static SWIGTYPE_p_MyDatabase copy_MyDatabaseHandle(SWIGTYPE_p_MyDatabase value) {
    long cPtr = databaseJNI.copy_MyDatabaseHandle(SWIGTYPE_p_MyDatabase.getCPtr(value));
    return (cPtr == 0) ? null : new SWIGTYPE_p_MyDatabase(cPtr, false);
  }

  public static void delete_MyDatabaseHandle(SWIGTYPE_p_MyDatabase obj) {
    databaseJNI.delete_MyDatabaseHandle(SWIGTYPE_p_MyDatabase.getCPtr(obj));
  }

  public static void MyDatabaseHandle_assign(SWIGTYPE_p_MyDatabase obj, SWIGTYPE_p_MyDatabase value) {
    databaseJNI.MyDatabaseHandle_assign(SWIGTYPE_p_MyDatabase.getCPtr(obj), SWIGTYPE_p_MyDatabase.getCPtr(value));
  }

  public static MyDatabase MyDatabaseHandle_value(SWIGTYPE_p_MyDatabase obj) {
    return new MyDatabase(databaseJNI.MyDatabaseHandle_value(SWIGTYPE_p_MyDatabase.getCPtr(obj)), true);
  }

  public static SWIGTYPE_p_p_MyCollection new_MyCollectionHandle() {
    long cPtr = databaseJNI.new_MyCollectionHandle();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_MyCollection(cPtr, false);
  }

  public static SWIGTYPE_p_p_MyCollection copy_MyCollectionHandle(MyCollection value) {
    long cPtr = databaseJNI.copy_MyCollectionHandle(MyCollection.getCPtr(value), value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_MyCollection(cPtr, false);
  }

  public static void delete_MyCollectionHandle(SWIGTYPE_p_p_MyCollection obj) {
    databaseJNI.delete_MyCollectionHandle(SWIGTYPE_p_p_MyCollection.getCPtr(obj));
  }

  public static void MyCollectionHandle_assign(SWIGTYPE_p_p_MyCollection obj, MyCollection value) {
    databaseJNI.MyCollectionHandle_assign(SWIGTYPE_p_p_MyCollection.getCPtr(obj), MyCollection.getCPtr(value), value);
  }

  public static MyCollection MyCollectionHandle_value(SWIGTYPE_p_p_MyCollection obj) {
    long cPtr = databaseJNI.MyCollectionHandle_value(SWIGTYPE_p_p_MyCollection.getCPtr(obj));
    return (cPtr == 0) ? null : new MyCollection(cPtr, false);
  }

}
