/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package gg.hc.mydatabase;

public class MyDatabase {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MyDatabase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MyDatabase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    databaseJNI.MyDatabase_name_set(swigCPtr, value);
  }

  public String getName() {
    return databaseJNI.MyDatabase_name_get(swigCPtr);
  }

  public void setFPtr(SWIGTYPE_p_f_p_q_const__char__int value) {
    databaseJNI.MyDatabase_fPtr_set(swigCPtr, SWIGTYPE_p_f_p_q_const__char__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__char__int getFPtr() {
    long cPtr = databaseJNI.MyDatabase_fPtr_get(swigCPtr);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__char__int(cPtr, false);
  }

}
